### ISSUE TITLE
Error while validating file: Cannot read property 'getAllModesInDocument'

### ISSUE THREAD

**Issue by ghost** [vscode-langservers/vscode-html-languageserver-bin#3]
Hello! Thank you for your fantastic work extracting the servers. Both JSON and CSS seem to be working fine. HTML, however, gives me a bit of a trouble. Would you please be able to advise whether this is a genuine issue or is it just me misconfiguring something?

Steps to reproduce:

1. Run `docker pull kaioakly/devenv` (an image with a simple development environment  + neovim, where the html language server is installed following the provided instructions; the repository with the Dockerfile is at https://hub.docker.com/r/kaioakly/devenv/).
2. Run `docker run -ti kaioakly/devenv`.
3. Create an empty .html file, e.g. hello.html.
4. Open the file in neovim: `nvim hello.html`.
5. The language server launches with an error below.

```
[Error] Error while validating file:///root/hello.html: Cannot read property 'getAllModesInDocument' of undefined^@TypeError: Cannot read property 'getAllModesInDocument' of u
ndefined^@    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:242:45^@    at step (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMai
n.js:37:23)^@    at Object.next (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:18:53)^@    at /usr/lib/node_modules/vscode-html-languageserver-bin/htm
lServerMain.js:12:71^@    at new Promise (<anonymous>)^@    at __awaiter (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:8:12)^@    at validateTextDocu
ment (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:233:12)^@    at Timeout._onTimeout (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServe
rMain.js:221:9)^@    at ontimeout (timers.js:427:11)^@    at tryOnTimeout (timers.js:289:5)
```

**Comment by MartenBE** [comment]
I am having the same problem when opening html files with neovim.
Used plugins for LSP-completion:
- Shougo/deoplete.nvim
- junegunn/fzf
- autozimu/LanguageClient-neovim

The error appears as soon as neovim opens an html file:

Error while validating file:///home/martijn/git/personal-kanban/backend/views/index.html: Cannot read property 'getAllModesInDocument' of undefined
```
TypeError: Cannot read property 'getAllModesInDocument' of undefined
    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:242:45
    at step (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:37:23)
    at Object.next (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:18:53)
    at /usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:8:12)
    at validateTextDocument (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:233:12)
    at Timeout._onTimeout (/usr/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js:221:9)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
```
As the error is coming from the server, the bug seems to be here. Could this be verified?

**Comment by MartenBE** [comment]
This issue was a bug in the LSP plugin of neovim and has been solved (https://github.com/autozimu/LanguageClient-neovim/issues/494). This issue can be closed.

**Comment by DeltaEvo** [comment]
Sorry for not having been here to help

**Comment by MartenBE** [comment]
No problem, the error wasn't here :)

In the mean time I've posted some other issues at https://github.com/autozimu/LanguageClient-neovim, as I wasn't sure if they belonged here or there:

- https://github.com/autozimu/LanguageClient-neovim/issues/498
- https://github.com/autozimu/LanguageClient-neovim/issues/499
- https://github.com/autozimu/LanguageClient-neovim/issues/500

Please let me know if you want me to make separate issues on here, or if you want this comment deleted.

**Comment by DeltaEvo** [comment]
I've responded to some
PS: No need to delete it
