### ISSUE TITLE
Server initialization failure.

### ISSUE THREAD

**Issue by shoorlyne** [vscode-langservers/vscode-html-languageserver-bin#4]
I am trying to connect Monaco editor to vscode-html-languageserver-bin, and I am having some issue.

My setup: Ubuntu/16.04.

It fails when the editor sends an initialization request to the server. The request sent over the wire looks like:

`{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"rootPath":null,"rootUri":"file:///home","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true},"dynamicRegistration":true},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true}}},"initializationOptions":{"storagePath":"/","gocodeCompletionEnabled":true},"trace":"off"}}`

The server responds with:

`{"jsonrpc":"2.0","id":0,"error":{"code":-32603,"message":"Request initialize failed with message: Cannot read property 'css' of undefined"}}
`

Any idea why this happens, and how I can fix it?

Thanks!

**Comment by DeltaEvo** [comment]
I don't really now what it's going on because it's not my code :sweat_smile:, but if we can have more information on the error, I can try to help. A full stack trace should be printed as log notification or in the stderr of the `vscode-html-languageserver-bin` process

**Comment by DeltaEvo** [comment]
Have you solved your issue ?

**Comment by sw-uedan** [comment]
I have same issue.
I'm using NeoVim with [vim-lsp](https://github.com/prabirshrestha/vim-lsp) plugin on Mac .

vim-lsp's logs:
```
["<---", 4, "html-languageserver", {"response": {"id": 1, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Request initialize failed with message: Cannot read property 'css' of undefined"}}, "request": {"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///Users/me", "initializationOptions": {}, "capabilities": {"workspace": {"applyEdit ": true}}, "rootPath": "/Users/me", "trace": "off"}}}]
```
> A full stack trace should be printed as log notification or in the stderr of the vscode-html-languageserver-bin process

Sorry, I couldn't get these log or stderr.. How could I get these?

Thanks.

**Comment by kyoz** [comment]
I do get the same issue with vim-lsp

```
if executable('html-languageserver')
  au User lsp_setup call lsp#register_server({
      \ 'name': 'html-languageserver',
      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'html-languageserver --stdio']},
      \ 'whitelist': ['html', 'javascript', 'typescript'],
      \ })
endif

```

**Comment by newmankyle** [comment]
Had to debug this with kakoune, so I thought I'd leave my findings. 

The version of html-languageserver this package depends requires either:
* embeddedLanguages property to be set on initializationOptions or
* initializationOptions to be absent

if you don't, it'll crash.

[Source](https://github.com/prabirshrestha/vim-lsp/pull/323)
